#!/usr/bin/env ruby
require 'bundler'
gems_by_name = {}
Bundler.load.specs.sort_by(&:name).each do |spec|
  gem = "#{spec.name} (#{spec.version}#{spec.git_version})"
  spec.authors.each do |name|
    if gems_by_name.key?(name)
      gems_by_name[name].push(gem)
    else
      gems_by_name[name] = [gem]
    end
  end
end

gems_by_name.sort_by! { |name, _| name.downcase }

gems_by_name.each do |name, gems|
  puts "#{name}: #{gems.sort.join ', '}"
end
