#!/usr/bin/env ruby
require 'bundler'

gems_by_name = {}
Bundler.load.specs.sort_by(&:name).each do |spec|
  gem = spec.name
  spec.authors.each do |name|
    if gems_by_name.key?(name)
      gems_by_name[name].push(gem)
    else
      gems_by_name[name] = [gem]
    end
  end
end

names = gems_by_name.keys

names.sort_by! { |name, _| name.downcase }

names.each do |name|
  puts "#{name}: #{gems_by_name[name].sort.join ', '}"
end
